### PR TITLE
shmounts: terminate the forked off mount namespace capture helper

### LINKED ISSUE #13158: On Noble, `setup-shmounts` sometimes fail, preventing snap to be purged
LXD `latest/candidate` **sometimes** fails to purge cleanly. Here's a script that sometimes reproduces the issue (I had 3 successive successful runs):

```
#!/bin/sh
set -u

lxc launch ubuntu-daily:24.04 v1 --vm

echo "==> Waiting for system to boot"
sleep 30
lxc exec v1 -- systemctl --wait --quiet is-system-running

while :; do
    echo "==> Install lxd candidate snap"
    lxc exec v1 -- snap install lxd --candidate
    
    echo "==> Listing snaps"
    lxc exec v1 -- snap list
    
    echo "==> Checking /snap/ mounts"
    lxc exec v1 -- mount | grep /snap/
    
    echo "==> Manually starting lxd"
    lxc exec v1 -- snap start lxd
    
    echo "==> Init lxd"
    lxc exec v1 -- lxd init --auto
    
    echo "==> Check for the bogus mount"
    lxc exec v1 -- grep -wF "/var/snap/lxd/common/shmounts" /proc/mounts && break

    echo "==> Did not work, retrying"
    lxc exec v1 -- snap remove --purge lxd
done

echo "==> Reproducer worked, continuing"
    
echo "==> Checking /snap/ mounts"
lxc exec v1 -- mount | grep /snap/

echo "==> Check lxd logs"
lxc exec v1 -- journalctl -o cat -u snap.lxd.daemon.service | cat

echo "==> Highlight failures with shmounts"
lxc exec v1 -- journalctl -o cat -u snap.lxd.daemon.service --grep shmounts

echo "==> Try to purge lxd"
lxc exec v1 -- snap remove --purge lxd
``````

The expected output when the failure occurs looks like this:

```
Creating v1
Starting v1
==> Waiting for system to boot
==> Install lxd candidate snap
2024-03-14T21:22:07Z INFO Waiting for automatic snapd restart...
Warning: /snap/bin was not found in your $PATH. If you've not restarted your session since you
         installed snapd, try doing that. Please see https://forum.snapcraft.io/t/9469 for more
         details.

lxd (candidate) 5.21.0-0cbd19b from Canonical✓ installed
==> Listing snaps
Name    Version         Rev    Tracking          Publisher   Notes
core22  20240111        1122   latest/stable     canonical✓  base
lxd     5.21.0-0cbd19b  27700  latest/candidate  canonical✓  -
snapd   2.61.2          21184  latest/stable     canonical✓  snapd
==> Checking /snap/ mounts
/var/lib/snapd/snaps/snapd_21184.snap on /snap/snapd/21184 type squashfs (ro,nodev,relatime,errors=continue,threads=single)
/var/lib/snapd/snaps/snapd_21184.snap on /snap/snapd/21184 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/core22_1122.snap on /snap/core22/1122 type squashfs (ro,nodev,relatime,errors=continue,threads=single)
/var/lib/snapd/snaps/core22_1122.snap on /snap/core22/1122 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/lxd_27700.snap on /snap/lxd/27700 type squashfs (ro,nodev,relatime,errors=continue,threads=single)
/var/lib/snapd/snaps/lxd_27700.snap on /snap/lxd/27700 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide,x-gvfs-hide)
==> Manually starting lxd
Started.
==> Init lxd
==> Check for the bogus mount
==> Did not work, retrying
2024-03-14T21:22:58Z INFO Waiting for "snap.lxd.daemon.unix.socket", "snap.lxd.daemon.service" to stop.
lxd removed
==> Install lxd candidate snap
lxd (candidate) 5.21.0-0cbd19b from Canonical✓ installed
==> Listing snaps
Name    Version         Rev    Tracking          Publisher   Notes
core22  20240111        1122   latest/stable     canonical✓  base
lxd     5.21.0-0cbd19b  27700  latest/candidate  canonical✓  -
snapd   2.61.2          21184  latest/stable     canonical✓  snapd
==> Checking /snap/ mounts
/var/lib/snapd/snaps/snapd_21184.snap on /snap/snapd/21184 type squashfs (ro,nodev,relatime,errors=continue,threads=single)
/var/lib/snapd/snaps/snapd_21184.snap on /snap/snapd/21184 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/core22_1122.snap on /snap/core22/1122 type squashfs (ro,nodev,relatime,errors=continue,threads=single)
/var/lib/snapd/snaps/core22_1122.snap on /snap/core22/1122 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/lxd_27700.snap on /snap/lxd/27700 type squashfs (ro,nodev,relatime,errors=continue,threads=single)
/var/lib/snapd/snaps/lxd_27700.snap on /snap/lxd/27700 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide,x-gvfs-hide)
==> Manually starting lxd
Started.
==> Init lxd
==> Check for the bogus mount
==> Did not work, retrying
2024-03-14T21:23:20Z INFO Waiting for "snap.lxd.daemon.service" to stop.
lxd removed
==> Install lxd candidate snap
lxd (candidate) 5.21.0-0cbd19b from Canonical✓ installed
==> Listing snaps
Name    Version         Rev    Tracking          Publisher   Notes
core22  20240111        1122   latest/stable     canonical✓  base
lxd     5.21.0-0cbd19b  27700  latest/candidate  canonical✓  -
snapd   2.61.2          21184  latest/stable     canonical✓  snapd
==> Checking /snap/ mounts
/var/lib/snapd/snaps/snapd_21184.snap on /snap/snapd/21184 type squashfs (ro,nodev,relatime,errors=continue,threads=single)
/var/lib/snapd/snaps/snapd_21184.snap on /snap/snapd/21184 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/core22_1122.snap on /snap/core22/1122 type squashfs (ro,nodev,relatime,errors=continue,threads=single)
/var/lib/snapd/snaps/core22_1122.snap on /snap/core22/1122 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/lxd_27700.snap on /snap/lxd/27700 type squashfs (ro,nodev,relatime,errors=continue,threads=single)
/var/lib/snapd/snaps/lxd_27700.snap on /snap/lxd/27700 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide,x-gvfs-hide)
==> Manually starting lxd
Started.
==> Init lxd
==> Check for the bogus mount
/dev/sda1 /var/snap/lxd/common/shmounts ext4 rw,relatime,discard,errors=remount-ro,commit=30 0 0
==> Reproducer worked, continuing
==> Checking /snap/ mounts
/var/lib/snapd/snaps/snapd_21184.snap on /snap/snapd/21184 type squashfs (ro,nodev,relatime,errors=continue,threads=single)
/var/lib/snapd/snaps/snapd_21184.snap on /snap/snapd/21184 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/core22_1122.snap on /snap/core22/1122 type squashfs (ro,nodev,relatime,errors=continue,threads=single)
/var/lib/snapd/snaps/core22_1122.snap on /snap/core22/1122 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide,x-gvfs-hide)
/var/lib/snapd/snaps/lxd_27700.snap on /snap/lxd/27700 type squashfs (ro,nodev,relatime,errors=continue,threads=single)
/var/lib/snapd/snaps/lxd_27700.snap on /snap/lxd/27700 type squashfs (ro,nodev,relatime,errors=continue,threads=single,x-gdu.hide,x-gvfs-hide)
tmpfs on /var/snap/lxd/common/ns type tmpfs (rw,relatime,size=1024k,mode=700,inode64)
nsfs on /var/snap/lxd/common/ns/shmounts type nsfs (rw)
/dev/sda1 on /var/snap/lxd/common/shmounts type ext4 (rw,relatime,discard,errors=remount-ro,commit=30)
==> Check lxd logs
Started snap.lxd.daemon.service - Service for snap application lxd.daemon.
=> Preparing the system (27700)
==> Loading snap configuration
==> Creating /var/snap/lxd/common/lxd/logs
==> Creating /var/snap/lxd/common/global-conf
==> Setting up mntns symlink (mnt:[4026532549])
==> Setting up mount propagation on /var/snap/lxd/common/lxd/storage-pools
==> Setting up mount propagation on /var/snap/lxd/common/lxd/devices
==> Setting up persistent shmounts path
====> Making LXD shmounts use the persistent path
====> Making LXCFS use the persistent path
==> Setting up kmod wrapper
==> Preparing /boot
==> Preparing a clean copy of /run
==> Preparing /run/bin
==> Preparing a clean copy of /etc
==> Preparing a clean copy of /usr/share/misc
==> Setting up ceph configuration
==> Setting up LVM configuration
==> Setting up OVN configuration
==> Rotating logs
==> Setting up ZFS (2.2)
==> Escaping the systemd cgroups
====> Detected cgroup V2
==> Escaping the systemd process resource limits
==> Increasing the number of inotify user instances
==> Increasing the number of keys for a nonroot user
==> Increasing the number of bytes for a nonroot user
==> Disabling Apparmor unprivileged userns mediation
==> Enabling LXD UI
==> Exposing LXD documentation
=> Starting LXCFS
Running constructor lxcfs_init to reload liblxcfs
mount namespace: 5
hierarchies:
  0: fd:   6: cpuset,cpu,io,memory,hugetlb,pids,rdma,misc
Kernel supports pidfds
Kernel does not support swap accounting
api_extensions:
- cgroups
- sys_cpu_online
- proc_cpuinfo
- proc_diskstats
- proc_loadavg
- proc_meminfo
- proc_stat
- proc_swaps
- proc_uptime
- proc_slabinfo
- shared_pidns
- cpuview_daemon
- loadavg_daemon
- pidfds
=> Starting LXD
time="2024-03-14T21:22:50Z" level=warning msg=" - Couldn't find the CGroup network priority controller, per-instance network priority will be ignored. Please use per-device limits.priority instead"
=> First LXD execution on this system
=> LXD is ready
Stopping snap.lxd.daemon.service - Service for snap application lxd.daemon...
=> Stop reason is: snap removal
=> Stopping LXD (with instance shutdown)
=> LXD exited cleanly
==> Stopped LXD
=> Stopping LXCFS
Running destructor lxcfs_exit
==> Stopped LXCFS
=> Cleaning up PID files
=> Cleaning up namespaces
=> All done
snap.lxd.daemon.service: Deactivated successfully.
Stopped snap.lxd.daemon.service - Service for snap application lxd.daemon.
snap.lxd.daemon.service: Consumed 1.003s CPU time, 54.3M memory peak, 0B memory swap peak.
Started snap.lxd.daemon.service - Service for snap application lxd.daemon.
=> Preparing the system (27700)
==> Loading snap configuration
==> Creating /var/snap/lxd/common/lxd/logs
==> Creating /var/snap/lxd/common/global-conf
==> Setting up mntns symlink (mnt:[4026532549])
==> Setting up mount propagation on /var/snap/lxd/common/lxd/storage-pools
==> Setting up mount propagation on /var/snap/lxd/common/lxd/devices
==> Setting up persistent shmounts path
====> Making LXD shmounts use the persistent path
====> Making LXCFS use the persistent path
==> Setting up kmod wrapper
==> Preparing /boot
==> Preparing a clean copy of /run
==> Preparing /run/bin
==> Preparing a clean copy of /etc
==> Preparing a clean copy of /usr/share/misc
==> Setting up ceph configuration
==> Setting up LVM configuration
==> Setting up OVN configuration
==> Rotating logs
==> Setting up ZFS (2.2)
==> Escaping the systemd cgroups
====> Detected cgroup V2
==> Escaping the systemd process resource limits
==> Enabling LXD UI
==> Exposing LXD documentation
=> Starting LXCFS
Running constructor lxcfs_init to reload liblxcfs
mount namespace: 5
hierarchies:
  0: fd:   6: cpuset,cpu,io,memory,hugetlb,pids,rdma,misc
Kernel supports pidfds
Kernel does not support swap accounting
api_extensions:
- cgroups
- sys_cpu_online
- proc_cpuinfo
- proc_diskstats
- proc_loadavg
- proc_meminfo
- proc_stat
- proc_swaps
- proc_uptime
- proc_slabinfo
- shared_pidns
- cpuview_daemon
- loadavg_daemon
- pidfds
=> Starting LXD
time="2024-03-14T21:23:14Z" level=warning msg=" - Couldn't find the CGroup network priority controller, per-instance network priority will be ignored. Please use per-device limits.priority instead"
=> First LXD execution on this system
=> LXD is ready
Stopping snap.lxd.daemon.service - Service for snap application lxd.daemon...
=> Stop reason is: snap removal
=> Stopping LXD (with instance shutdown)
=> LXD exited cleanly
==> Stopped LXD
=> Stopping LXCFS
Running destructor lxcfs_exit
==> Stopped LXCFS
=> Cleaning up PID files
=> Cleaning up namespaces
=> All done
snap.lxd.daemon.service: Deactivated successfully.
Stopped snap.lxd.daemon.service - Service for snap application lxd.daemon.
Started snap.lxd.daemon.service - Service for snap application lxd.daemon.
=> Preparing the system (27700)
==> Loading snap configuration
==> Creating /var/snap/lxd/common/lxd/logs
==> Creating /var/snap/lxd/common/global-conf
==> Setting up mntns symlink (mnt:[4026532549])
==> Setting up mount propagation on /var/snap/lxd/common/lxd/storage-pools
==> Setting up mount propagation on /var/snap/lxd/common/lxd/devices
==> Setting up persistent shmounts path
Failed to bind-mount /var/snap/lxd/common/shmounts to /media/.lxd-shmounts: No such file or directory
Failed to setup the shmounts namespace: No such file or directory
====> Failed to setup shmounts, continuing without
====> Making LXD shmounts use the persistent path
====> Making LXCFS use the persistent path
==> Setting up kmod wrapper
==> Preparing /boot
==> Preparing a clean copy of /run
==> Preparing /run/bin
==> Preparing a clean copy of /etc
==> Preparing a clean copy of /usr/share/misc
==> Setting up ceph configuration
==> Setting up LVM configuration
==> Setting up OVN configuration
==> Rotating logs
==> Setting up ZFS (2.2)
==> Escaping the systemd cgroups
====> Detected cgroup V2
==> Escaping the systemd process resource limits
==> Enabling LXD UI
==> Exposing LXD documentation
=> Starting LXCFS
Running constructor lxcfs_init to reload liblxcfs
mount namespace: 5
hierarchies:
  0: fd:   6: cpuset,cpu,io,memory,hugetlb,pids,rdma,misc
Kernel supports pidfds
Kernel does not support swap accounting
api_extensions:
- cgroups
- sys_cpu_online
- proc_cpuinfo
- proc_diskstats
- proc_loadavg
- proc_meminfo
- proc_stat
- proc_swaps
- proc_uptime
- proc_slabinfo
- shared_pidns
- cpuview_daemon
- loadavg_daemon
- pidfds
=> Starting LXD
time="2024-03-14T21:23:38Z" level=warning msg=" - Couldn't find the CGroup network priority controller, per-instance network priority will be ignored. Please use per-device limits.priority instead"
=> First LXD execution on this system
=> LXD is ready
==> Highlight failures with shmounts
==> Setting up persistent shmounts path
====> Making LXD shmounts use the persistent path
==> Setting up persistent shmounts path
====> Making LXD shmounts use the persistent path
==> Setting up persistent shmounts path
Failed to bind-mount /var/snap/lxd/common/shmounts to /media/.lxd-shmounts: No such file or directory
Failed to setup the shmounts namespace: No such file or directory
====> Failed to setup shmounts, continuing without
====> Making LXD shmounts use the persistent path
==> Try to purge lxd
2024-03-14T21:23:44Z INFO Waiting for "snap.lxd.daemon.unix.socket", "snap.lxd.daemon.service" to stop.
error: cannot perform the following tasks:
- Stop snap "lxd" services (systemctl command [--no-reload enable snap.lxd.daemon.unix.socket snap.lxd.user-daemon.unix.socket snap.lxd.activate.service] failed with exit status 1: stderr:
Failed to enable unit: Unit file snap.lxd.daemon.unix.socket does not exist.)
- Remove data for snap "lxd" (27700) (unlinkat /var/snap/lxd/common/shmounts: device or resource busy)
```

### PR DESCRIPTION
**Pull request by bboozzoo**
Make sure to terminate the forked off mount namespace capture helper, otherwise the child will continue execution of the remaining setup code and thus cause a race with the parent which occasionally manifests itself with the /var/snap/lxd/common/shmounts being missing from the parennt's mount namespace after it has switched back to the moutn ns of pid 1.

Fixes https://github.com/canonical/lxd/issues/13158

### CODE REVIEW

**Comment by bboozzoo** [comment]
cc @zyga please have a look, whether looks reasonable.

**Review by tomponline — APPROVED** [review]
Thanks!

File: shmounts/setup-shmounts.c [hunk 1]
```diff
@@ -66,6 +66,12 @@ int mkdir_p(const char *dir, mode_t mode)
 	return 0;
 }
 
+__attribute__((noreturn))
+static void die(const char *s)  {
+	perror(s);
```
Comment (zyga) [inline shmounts/setup-shmounts.c:71]: This will display the value of errno. This is fine but may be non-obvious during usage.

File: shmounts/setup-shmounts.c [hunk 2]
```diff
@@ -94,40 +100,41 @@ int setup_ns() {
...
 		close(fd);
 
 		if (mount(nspath, "/var/snap/lxd/common/ns/shmounts", NULL, MS_BIND, NULL) < 0) {
-			return -1;
+			die("cannot bind mount ns to /var/snap/lxd/common/ns/shmounts");
 		}
 
-		return 0;
+		/* the child is done */
+		exit(0);
```
Comment (zyga) [inline shmounts/setup-shmounts.c:137]: Thank you for catching this! This is indeed essential.

**Review by zyga — APPROVED** [review]

**Comment by tomponline** [comment]
Shall I merge this so we can get a fix into the edge builds ASAP?

**Comment by tomponline** [comment]
I'll merge for now and the error messages can be improved later. Thanks again!
